export const DEFAULT_SOLUTIONS = [
  { name: 'MSX',                  trademark: '®', logoKey: 'msx',           sortOrder: 1 },
  { name: 'MSXCyber',             trademark: '®', logoKey: 'msxCyber',      sortOrder: 2 },
  { name: 'ESG',                  trademark: '',  logoKey: 'xgrcMaster',    sortOrder: 3 },
  { name: 'SHEQX',                trademark: '®', logoKey: 'sheqx',         sortOrder: 4 },
  { name: 'ERM',                  trademark: '',  logoKey: 'erm',           sortOrder: 5 },
  { name: 'Integrated Assurance', trademark: '',  logoKey: 'xgrcMaster',    sortOrder: 6 },
  { name: 'ENVIRX',               trademark: '®', logoKey: 'envirx',        sortOrder: 7 },
  { name: 'XGRC Compliance Hub',  trademark: '®', logoKey: 'complianceHub', sortOrder: 8 },
  { name: 'XLOGIC',               trademark: '®', logoKey: 'xlogic',        sortOrder: 9 },
  { name: 'MAIA',                 trademark: '®', logoKey: 'maia',          sortOrder: 10 },
  { name: 'HAKWARE',              trademark: '',  logoKey: 'archangel',     sortOrder: 11 },
]

export const DEFAULT_TOPICS = [
  // Governance & Risk
  {
    title: 'Enterprise Risk Management (ERM): Why integrated risk visibility matters',
    value: 'Enterprise Risk Management',
    category: 'Governance & Risk',
    logoKey: 'erm',
    hashtags: JSON.stringify(['#EnterpriseRisk', '#ERM', '#RiskManagement', '#RiskVisibility', '#GRC']),
    sortOrder: 1,
  },
  {
    title: 'Combined Assurance: Breaking down silos between audit, risk, and compliance',
    value: 'Combined Assurance',
    category: 'Governance & Risk',
    logoKey: 'xgrcMaster',
    hashtags: JSON.stringify(['#CombinedAssurance', '#InternalAudit', '#RiskManagement', '#GRC', '#IntegratedGovernance']),
    sortOrder: 2,
  },
  {
    title: 'Governance Maturity: How boards are evolving their oversight approach',
    value: 'Governance Maturity',
    category: 'Governance & Risk',
    logoKey: 'xgrcMaster',
    hashtags: JSON.stringify(['#Governance', '#BoardGovernance', '#GRC', '#RiskOversight', '#GovernanceMaturity']),
    sortOrder: 3,
  },
  {
    title: 'Risk Intelligence: Moving from reactive to proactive risk management',
    value: 'Risk Intelligence',
    category: 'Governance & Risk',
    logoKey: 'erm',
    hashtags: JSON.stringify(['#RiskIntelligence', '#ERM', '#ProactiveRisk', '#GRC', '#RiskManagement']),
    sortOrder: 4,
  },
  {
    title: 'Internal Audit Transformation: The shift from box-ticking to strategic assurance',
    value: 'Internal Audit Transformation',
    category: 'Governance & Risk',
    logoKey: 'xgrcMaster',
    hashtags: JSON.stringify(['#InternalAudit', '#Assurance', '#GRC', '#RiskManagement', '#AuditTransformation']),
    sortOrder: 5,
  },
  {
    title: 'Policy Governance: Building a culture of accountability',
    value: 'Policy Governance',
    category: 'Governance & Risk',
    logoKey: 'xgrcMaster',
    hashtags: JSON.stringify(['#PolicyGovernance', '#Accountability', '#GRC', '#Compliance', '#RiskCulture']),
    sortOrder: 6,
  },
  {
    title: 'Risk Appetite Frameworks: Setting boundaries that enable growth',
    value: 'Risk Appetite Frameworks',
    category: 'Governance & Risk',
    logoKey: 'erm',
    hashtags: JSON.stringify(['#RiskAppetite', '#ERM', '#RiskManagement', '#GRC', '#StrategicRisk']),
    sortOrder: 7,
  },
  {
    title: 'Three Lines of Defence: Making the model work in practice',
    value: 'Three Lines of Defence',
    category: 'Governance & Risk',
    logoKey: 'xgrcMaster',
    hashtags: JSON.stringify(['#ThreeLinesOfDefence', '#InternalAudit', '#GRC', '#RiskManagement', '#Governance']),
    sortOrder: 8,
  },
  // Compliance & Regulatory
  {
    title: 'Continuous Compliance: Why point-in-time audits are no longer enough',
    value: 'Continuous Compliance',
    category: 'Compliance & Regulatory',
    logoKey: 'xgrcMaster',
    hashtags: JSON.stringify(['#ContinuousCompliance', '#Compliance', '#GRC', '#RegulatoryCompliance', '#DrivingCompliance']),
    sortOrder: 9,
  },
  {
    title: 'POPIA Compliance: What South African organisations need to know',
    value: 'POPIA Compliance',
    category: 'Compliance & Regulatory',
    logoKey: 'xgrcMaster',
    hashtags: JSON.stringify(['#POPIA', '#DataPrivacy', '#Compliance', '#SouthAfrica', '#GRC']),
    sortOrder: 10,
  },
  {
    title: 'GDPR in Practice: Operationalising data privacy governance',
    value: 'GDPR in Practice',
    category: 'Compliance & Regulatory',
    logoKey: 'xgrcMaster',
    hashtags: JSON.stringify(['#GDPR', '#DataPrivacy', '#Compliance', '#DataGovernance', '#GRC']),
    sortOrder: 11,
  },
  {
    title: 'ISO 27001 Certification: The business case beyond the certificate',
    value: 'ISO 27001 Certification',
    category: 'Compliance & Regulatory',
    logoKey: 'msxCyber',
    hashtags: JSON.stringify(['#ISO27001', '#Cybersecurity', '#InformationSecurity', '#CyberResilience', '#GRC']),
    sortOrder: 12,
  },
  {
    title: 'Compliance Automation: Reducing manual effort without losing rigour',
    value: 'Compliance Automation',
    category: 'Compliance & Regulatory',
    logoKey: 'xgrcMaster',
    hashtags: JSON.stringify(['#ComplianceAutomation', '#Compliance', '#GRC', '#DrivingCompliance', '#RegTech']),
    sortOrder: 13,
  },
  {
    title: 'Regulatory Readiness: Staying ahead of evolving requirements',
    value: 'Regulatory Readiness',
    category: 'Compliance & Regulatory',
    logoKey: 'xgrcMaster',
    hashtags: JSON.stringify(['#RegulatoryReadiness', '#Compliance', '#GRC', '#RegulatoryRisk', '#DrivingCompliance']),
    sortOrder: 14,
  },
  {
    title: 'Compliance as a Business Enabler: Reframing the narrative',
    value: 'Compliance as a Business Enabler',
    category: 'Compliance & Regulatory',
    logoKey: 'xgrcMaster',
    hashtags: JSON.stringify(['#Compliance', '#BusinessEnablement', '#GRC', '#DrivingCompliance', '#RegulatoryCompliance']),
    sortOrder: 15,
  },
  // Cybersecurity
  {
    title: 'Cyber Resilience vs Cybersecurity: Understanding the difference',
    value: 'Cyber Resilience',
    category: 'Cybersecurity',
    logoKey: 'msxCyber',
    hashtags: JSON.stringify(['#Cybersecurity', '#CyberResilience', '#InfoSec', '#CyberRisk', '#ISO27001']),
    sortOrder: 16,
  },
  {
    title: 'NIST CSF: Practical implementation for enterprise organisations',
    value: 'NIST CSF Implementation',
    category: 'Cybersecurity',
    logoKey: 'msxCyber',
    hashtags: JSON.stringify(['#NISTCSF', '#Cybersecurity', '#CyberFramework', '#InfoSec', '#CyberRisk']),
    sortOrder: 17,
  },
  {
    title: 'Vulnerability Management: From discovery to remediation',
    value: 'Vulnerability Management',
    category: 'Cybersecurity',
    logoKey: 'archangel',
    hashtags: JSON.stringify(['#VulnerabilityManagement', '#Cybersecurity', '#CyberRisk', '#ThreatIntelligence', '#ISO27001']),
    sortOrder: 18,
  },
  {
    title: 'Incident Response Planning: Are you ready when it happens?',
    value: 'Incident Response Planning',
    category: 'Cybersecurity',
    logoKey: 'msxCyber',
    hashtags: JSON.stringify(['#IncidentResponse', '#Cybersecurity', '#CyberResilience', '#InfoSec', '#CyberRisk']),
    sortOrder: 19,
  },
  {
    title: 'Identity & Access Management: Closing the insider threat gap',
    value: 'Identity and Access Management',
    category: 'Cybersecurity',
    logoKey: 'msxCyber',
    hashtags: JSON.stringify(['#IAM', '#IdentityManagement', '#Cybersecurity', '#ZeroTrust', '#InfoSec']),
    sortOrder: 20,
  },
  {
    title: 'Cloud Security Governance: Managing risk in hybrid environments',
    value: 'Cloud Security Governance',
    category: 'Cybersecurity',
    logoKey: 'msxCyber',
    hashtags: JSON.stringify(['#CloudSecurity', '#Cybersecurity', '#CloudGovernance', '#InfoSec', '#CyberRisk']),
    sortOrder: 21,
  },
  {
    title: 'SIEM & Continuous Monitoring: Visibility is not optional',
    value: 'SIEM and Continuous Monitoring',
    category: 'Cybersecurity',
    logoKey: 'msxCyber',
    hashtags: JSON.stringify(['#SIEM', '#ContinuousMonitoring', '#Cybersecurity', '#ThreatDetection', '#InfoSec']),
    sortOrder: 22,
  },
  // ESG & Sustainability
  {
    title: 'ESG Governance: Why boards need a structured oversight framework',
    value: 'ESG Governance',
    category: 'ESG & Sustainability',
    logoKey: 'xgrcMaster',
    hashtags: JSON.stringify(['#ESG', '#Sustainability', '#ESGGovernance', '#CorporateGovernance', '#ESGReporting']),
    sortOrder: 23,
  },
  {
    title: 'Sustainability Reporting: Moving from narrative to measurable KPIs',
    value: 'Sustainability Reporting',
    category: 'ESG & Sustainability',
    logoKey: 'xgrcMaster',
    hashtags: JSON.stringify(['#SustainabilityReporting', '#ESG', '#ESGData', '#CorporateGovernance', '#GRI']),
    sortOrder: 24,
  },
  {
    title: 'ESG Data Integrity: Building trust through accurate reporting',
    value: 'ESG Data Integrity',
    category: 'ESG & Sustainability',
    logoKey: 'xgrcMaster',
    hashtags: JSON.stringify(['#ESGData', '#ESG', '#DataIntegrity', '#SustainabilityReporting', '#ESGGovernance']),
    sortOrder: 25,
  },
  {
    title: 'Environmental Risk: Integrating climate into enterprise risk management',
    value: 'Environmental Risk Management',
    category: 'ESG & Sustainability',
    logoKey: 'xgrcMaster',
    hashtags: JSON.stringify(['#EnvironmentalRisk', '#ESG', '#ClimateRisk', '#ERM', '#Sustainability']),
    sortOrder: 26,
  },
  // Technology & Digital
  {
    title: 'AI in GRC: How artificial intelligence is transforming governance',
    value: 'AI in GRC',
    category: 'Technology & Digital',
    logoKey: 'maia',
    hashtags: JSON.stringify(['#AIGovernance', '#GRC', '#DigitalGovernance', '#AI', '#ComplianceTech']),
    sortOrder: 27,
  },
  {
    title: 'Integrated GRC Platforms: The case for a single source of truth',
    value: 'Integrated GRC Platforms',
    category: 'Technology & Digital',
    logoKey: 'xgrcMaster',
    hashtags: JSON.stringify(['#GRC', '#IntegratedGovernance', '#GRCPlatform', '#Compliance', '#RiskManagement']),
    sortOrder: 28,
  },
  {
    title: 'Workflow Automation in Compliance: Reducing friction, improving outcomes',
    value: 'Workflow Automation in Compliance',
    category: 'Technology & Digital',
    logoKey: 'xgrcMaster',
    hashtags: JSON.stringify(['#WorkflowAutomation', '#Compliance', '#GRC', '#RegTech', '#ComplianceAutomation']),
    sortOrder: 29,
  },
  {
    title: 'Real-Time Dashboards: Enabling data-driven governance decisions',
    value: 'Real-Time Dashboards',
    category: 'Technology & Digital',
    logoKey: 'pix',
    hashtags: JSON.stringify(['#KPIs', '#PerformanceIndicators', '#Dashboards', '#GRC', '#DataDrivenGovernance']),
    sortOrder: 30,
  },
  {
    title: 'Vendor Risk Management: Managing third-party exposure at scale',
    value: 'Vendor Risk Management',
    category: 'Technology & Digital',
    logoKey: 'vcm',
    hashtags: JSON.stringify(['#VendorCompliance', '#SupplierRisk', '#ThirdPartyRisk', '#GRC', '#ProcurementCompliance']),
    sortOrder: 31,
  },
  // SHEQ & Operations
  {
    title: 'ISO 45001: Embedding occupational health and safety governance',
    value: 'ISO 45001',
    category: 'SHEQ & Operations',
    logoKey: 'sheqx',
    hashtags: JSON.stringify(['#SHEQ', '#HealthAndSafety', '#ISO45001', '#QualityManagement', '#OperationalSafety']),
    sortOrder: 32,
  },
  {
    title: 'SHEQ Integration: Aligning safety, health, environment, and quality',
    value: 'SHEQ Integration',
    category: 'SHEQ & Operations',
    logoKey: 'sheqx',
    hashtags: JSON.stringify(['#SHEQ', '#ISO45001', '#HealthAndSafety', '#QualityManagement', '#EnvironmentalManagement']),
    sortOrder: 33,
  },
  {
    title: 'Operational Resilience: Building organisations that recover faster',
    value: 'Operational Resilience',
    category: 'SHEQ & Operations',
    logoKey: 'xgrcMaster',
    hashtags: JSON.stringify(['#OperationalResilience', '#BusinessContinuity', '#GRC', '#RiskManagement', '#Resilience']),
    sortOrder: 34,
  },
  {
    title: 'Contractor Management: Governance beyond your own walls',
    value: 'Contractor Management',
    category: 'SHEQ & Operations',
    logoKey: 'sheqx',
    hashtags: JSON.stringify(['#ContractorManagement', '#SHEQ', '#SupplierRisk', '#HealthAndSafety', '#GRC']),
    sortOrder: 35,
  },
]
